apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: vaultName
      value: "phase5-secrets"
scopes:
  - backend
  - audit-agent
  - recurring-task-agent
  - reminder-agent
  - realtime-sync-agent
