apiVersion: v1
kind: Namespace
metadata:
  name: tracing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tracing
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          args:
            - "--memory.max-traces=10000"
            - "--query.base-path=/jaeger"
            - "--collector.zipkin.host-port=:9411"
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
            - name: PROMETHEUS_SERVER_URL
              value: "http://prometheus.monitoring:9090"
            - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
              value: "true"
            - name: PROMETHEUS_QUERY_NAMESPACE
              value: "span_metrics"
            - name: PROMETHEUS_QUERY_DURATION_UNIT
              value: "s"
          ports:
            # Agent ports
            - name: agent-compact
              containerPort: 6831
              protocol: UDP
            - name: agent-binary
              containerPort: 6832
              protocol: UDP
            - name: agent-configs
              containerPort: 5778
              protocol: TCP
            # Collector ports
            - name: collector-http
              containerPort: 14268
              protocol: TCP
            - name: collector-grpc
              containerPort: 14250
              protocol: TCP
            - name: collector-zipkin
              containerPort: 9411
              protocol: TCP
            # OTLP ports
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            # Query/UI port
            - name: query
              containerPort: 16686
              protocol: TCP
            # Admin port
            - name: admin
              containerPort: 14269
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: jaeger-data
              mountPath: /badger
      volumes:
        - name: jaeger-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: tracing
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  ports:
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: jaeger-collector-zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app: jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: tracing
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
spec:
  type: ClusterIP
  ports:
    - name: query
      port: 16686
      targetPort: 16686
      protocol: TCP
  selector:
    app: jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: tracing
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: agent-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: agent-binary
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: agent-configs
      port: 5778
      targetPort: 5778
      protocol: TCP
  selector:
    app: jaeger

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query
  namespace: tracing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: jaeger.phase5.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
